# Generated by Django 5.2.1 on 2025-06-01 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id_publisher', models.AutoField(primary_key=True, serialize=False)),
                ('naran_publisher', models.CharField(max_length=60)),
                ('enderesu', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('nu_telf', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
        ),
    ]
