# Generated by Django 5.2.1 on 2025-06-01 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id_autor', models.AutoField(primary_key=True, serialize=False)),
                ('naran_autor', models.CharField(max_length=60)),
            ],
        ),
    ]
