# Generated by Django 5.2.1 on 2025-06-02 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='data_moris',
            field=models.DateField(blank=True, null=True),
        ),
    ]
