# Generated by Django 5.2.1 on 2025-06-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0002_autor_data_moris'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='nasionalidade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
