# Generated by Django 5.2.1 on 2025-06-01 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0001_initial'),
        ('livru', '0001_initial'),
        ('publisher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livru',
            name='data_publica',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livru',
            name='id_autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autor.autor'),
        ),
        migrations.AlterField(
            model_name='livru',
            name='id_kategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='livru.kategoria'),
        ),
        migrations.AlterField(
            model_name='livru',
            name='id_publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publisher.publisher'),
        ),
    ]
