# Generated by Django 5.2.1 on 2025-06-01 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membru',
            fields=[
                ('id_membru', models.AutoField(primary_key=True, serialize=False)),
                ('naran_membru', models.CharField(max_length=100)),
                ('hela_fatin', models.CharField(max_length=50)),
                ('sexu', models.CharField(choices=[('M', 'Mane'), ('F', 'Feto')], default='M', max_length=5)),
                ('data_moris', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
